import { execSync } from 'child_process';
import { writeFileSync } from 'fs';

try {
  const output = execSync('nearleyc ./src/core/grammar.ne', { encoding: 'utf-8' }); // Runs the command and returns output as a string
  
  const lines = output.split('\n');

  // Remove shell generated by Nearley
  lines.splice(2, 3);
  lines.splice(-7);

  // Insert variable declaration after line 2
  lines.splice(2, 0, `/* eslint-disable no-useless-escape */
const grammar: nearley.CompiledRules = {`);

  // Insert export statement at the end

  lines.push('export default grammar;');

  const newOutput = lines.join('\n');
  
  // Write to ./src/core/grammar.ts
  writeFileSync('./src/core/grammar.ts', newOutput);
} catch (error) {
  console.error(error);
}
